### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by mathiasbockwoldt** [jcampbell1/simple-file-manager#102]
I really like the idea of a simple file manager that is easy to set up, easy to use and easy to remove again. Apparently, many other people appreciate the tool as well (almost 50 watchers, more than 600 stars and 340 forks). 

However, there are 44 open issues. Some were apparently solved, but the issues never closed. Some of these issues state severe security issues that are prohibitive to using this script without a password (e.g. #73 and #81) and it is not clear whether they were solved or not. The last comment by the author, @jcampbell1, (as far as I can see) was in May this year (#97) and the last commit is a pull request accepted in June this year. However, there are 15 other pull requests that are still open.

So is this repository still actively maintained? Is there any wish to develop it further? I like the idea of sticking to its simplicity, but bugs should be fixed and some feature requests should be easy to solve without complicating the script too much or increasing its file size, like modifying the working directory.

@jcampbell1, what are your plans for this small but very useful project?

**Comment by arnisjuraga** [comment]
I am willing to participate also.

**Comment by mathiasbockwoldt** [comment]
Thank you, @jcampbell1! Looks like you did a whole lot of work the last hours!

**Comment by jcampbell1** [comment]
Thanks, I have a bit more time to keep it maintained.
