### ISSUE TITLE
View files instead of saving or download prompt

### ISSUE THREAD

**Issue by ikwyl6** [jcampbell1/simple-file-manager#104]
When I click on pretty much any file it prompts me to download it. I would rather view it (txt or pdf as example). Is there a way to change the application/stream so it views the file instead of downloading it?

**Comment by jcampbell1** [comment]
When clicking a link, it should just request the file directly from the web
server.

Can you post an example request with the list of headers?

**Comment by ikwyl6** [comment]
Seems like when I add the mime-type into lighttpd and reload, it views the pdf...
