### ISSUE TITLE
Uncaught TypeError: data is null

### ISSUE THREAD

**Issue by fraucs** [jcampbell1/simple-file-manager#108]
hi in a page of my site the code doesn't work,
no files are shown.  :(

in my console:

`Uncaught TypeError: data is null
    list https://www.mysite.co/.../.../.../.../list.php:129
    jQuery 7
        k
        fireWith
        y
        d
        send
        ajax
        c
    list https://www.mysite.co/.../.../.../.../list.php:126
    jQuery 7
        dispatch
        h
        trigger
        trigger
        each
        each
        trigger
    <anonymous> https://www.mysite.co/.../.../.../.../list.php:104
    jQuery 11
        k
        fireWith
        ready
        D
        promise
        ready
        init
        p
        support
        <anonymous>
        <anonymous>
list.php:129:7`

Now, I wonder what could be causing that...

**Comment by coder0107git** [comment]
It looks like line 129 throws the error in list.php... It also references lines 126 and 104. Could you please attach those lines?

**Comment by fraucs** [comment]
Sorry for the delay, I no longer had the opportunity to recover what I asked, because I abandoned the project for personal reasons. 

BTW thanks for the support!
