### ISSUE TITLE
Special Characters folder

### ISSUE THREAD

**Issue by aleckssubtil** [jcampbell1/simple-file-manager#13]
It doesn't list nothing when there is a folder with special characters like á, é, ã, õ...
Just "crashes". No php errors. Only say "Uncaught TypeError: $(...).tablesorter is not a function
jquery.min.js:16 Uncaught TypeError: Cannot read property 'success' of null".

**Comment by jcampbell1** [comment]
I can't reproduce this one.

**Comment by eri451** [comment]
I have a similar problem. When creating a folder with a special char e.g. space in the name. I cannot open it. This does not apply on Chromium 60 but on Firefox 55. Firefox displays the correct URL but it seems that if your folder name would be "nice days" that Firefox 55 tries to get the list from the "nice" folder.
I tried trim() but finally i used preg_match() to exit the PHP-side of the AJAX.
Do you have a better way?
