### ISSUE TITLE
Its Not Listing A Directory

### ISSUE THREAD

**Issue by besoeasy** [jcampbell1/simple-file-manager#14]
The Script Works Fine On Home, But When U GO To A Directory It Doesn't Show The Files Inside Of It 

But There Is No Issue For My Friend, Only For Me 

Here Is The Example

This Won't Work
http://besoeasy.com/data/#[JulesJordan]%20Abella%20Anderson%20%28Anal%20Cruising%20South%20Beach%29%20[XXX]%20x264

This WIll

http://besoeasy.com/data/[JulesJordan]%20Abella%20Anderson%20%28Anal%20Cruising%20South%20Beach%29%20[XXX]%20x264

**Comment by efsysefsys** [comment]
same problem on nginx

**Comment by zyuhel** [comment]
Problem is seems to be with urldecoding. It works normally for me with chrome, and doesn't work in firefox.
As workaround i added additional check
`if ($tmp===false)
{
$_REQUEST['file']=urldecode($_REQUEST['file']);
$tmp = realpath($_REQUEST['file']);
}`
