### ISSUE TITLE
Ability to configure working directory

### ISSUE THREAD

**Issue by CheapApples12** [jcampbell1/simple-file-manager#19]
There really needs to be some way to change/configure the working directory. This is a really awesome system, however it's use is very limited without the ability to choose where the "home" directory is. This is definitely on my watch list, but I can't use it until there is some kind of feature allowing me to change the directory.

**Comment by alwaysontop617** [comment]
Yes, I think you are right

**Comment by TopHatProductions115** [comment]
Could chmod permissions help?

My inexperienced suggestion:
chown the php file under the applicable owner
chmod the desired working directory as the only folder visible to the chown'd php file
upload/move the php file to the desired workspace/working directory

I really want to use this project as well. Just putting one small cent (not two).

**Comment by jcampbell1** [comment]
I have changed things so you can symlink the script.  

You have two options.  Put the script in the folder you want.  Create a symlink to the script in the folder you want.

**Comment by TopHatProductions115** [comment]
Thank you
