### ISSUE TITLE
Remove the delete function

### ISSUE THREAD

**Issue by didimanoso** [jcampbell1/simple-file-manager#20]
Please tell me how to remove the delete function also with the delete button on index.php

**Comment by mesler1** [comment]
I think this would do it.  However, note that you can still overwrite a file with an empty (effectively blanking it).

28a29,30
> $allow_delete = false;
> 
57,58c59,60
< 	        	'is_deleteable' => (!is_dir($i) && is_writable($directory)) || 
< 	        					   (is_dir($i) && is_writable($directory) && is_recursively_deleteable($i)),
---
> 	        	'is_deleteable' => $allow_delete && ((!is_dir($i) && is_writable($directory)) || 
> 	        					   (is_dir($i) && is_writable($directory) && is_recursively_deleteable($i))),
70c72,74
< 	rmrf($file);
---
> 	if($allow_delete) {
> 		rmrf($file);
> 	}

**Comment by jcampbell1** [comment]
send a pull request with allow_delete at the top, and default to true.
I'll merge it.

**Comment by jcampbell1** [comment]
Looks like this has been merged.  Closing.
