### ISSUE TITLE
Add informational message if the directory/folder is not writeable

### ISSUE THREAD

**Issue by gitdeepsix** [jcampbell1/simple-file-manager#25]
Just a note that if the file manager directory is not writeable (ie. the web server does not have permission to write to the directory/folder) there is no explanation, the upload box just disappears. It took me a few minutes to work this out.

Would be more user friendly to add an informational message if the directory/folder is not writeable so as not to confuse the new user.

**Comment by jcampbell1** [comment]
This is useful to people without folder being writable.  Such users shouldn't see any message telling them they should change permissions, because it is likely they have it the way they want it.  

I have tweaked the README to make it easier for beginners to notice the requirement.

**Comment by gitdeepsix** [comment]
Yes I agree with you there. I guess I would replace the upload box with something elegant that indicated to the user that upload is not allowed but it's your choice. Thanks!
