### ISSUE TITLE
Two Feature Requests:

### ISSUE THREAD

**Issue by Jwink3101** [jcampbell1/simple-file-manager#38]
I am enjoying this code and using it in conjunction with [IFM](https://github.com/misterunknown/ifm).

However, I have two feature requests:

* Make a responsive interface that looks good on mobile browsers. It isn't too bad now, but could be a lot better
* Integrate a simple file editor for text files. 

Thanks!

**Comment by EduardoOliveira** [comment]
you can try my fork, it has been reimplemented as bootstrap so it should be more responsive

**Comment by czmole** [comment]
Probably this is meant to stick to its name to be a simple file manager: upload, download and browse :)
Just my humble opinion.
