### ISSUE TITLE
Cannot delete on IE

### ISSUE THREAD

**Issue by MickaelTH** [jcampbell1/simple-file-manager#45]
Hi,

Delete button doesn't seem to work on IE 11. When click on it nothing happens.

The link # is not understood by IE, maybe need to change for a form?

**Comment by snader** [comment]
Try to replace
$('.delete').live('click',function(data) {
with
$(document).on("click", ".delete", function(data) {

**Comment by MickaelTH** [comment]
Hi,

Thanks for answering. I tested on IE 11 on Win10, refreshing cache, emptied cache and also tried on inPrivate mode but this is still the same result: file is deleted on the disk but still appears on the list.

**Comment by MickaelTH** [comment]
Closing as this is getting old/unmaintained.
