### ISSUE TITLE
ZIP + UNZIP + EDIT

### ISSUE THREAD

**Issue by tazotodua** [jcampbell1/simple-file-manager#5]
here is comprehensive PHP file manager.
Add those functions to your filemanager too.

**Comment by AngeIII** [comment]
+1 would be nice to extract/zip/unzpi

**Comment by EduardoOliveira** [comment]
You can checkout my fork, it has a zip functionality but no warranties :p

**Comment by infostreams** [comment]
This fork: https://github.com/AngeIII/simple-file-manager can edit, zip and unzip, and rename files.

**Comment by AngeIII** [comment]
@infostreams , Thanks.

But please be carefoul with inlineedit I noticed that <br> tags being added while push newline.

Probably contentinline will be changed by simple textarea.
