### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by Josema1982** [jcampbell1/simple-file-manager#50]
Hi, I'm working on OS X and I'd like to hide .DS_Strore file, I've tried in hidden extensions settings with ''(empty) but doesn't work. Thanks in advance.

**Comment by jcampbell1** [comment]
the extensions must be lower case, so use:

$hidden_extensions = ['php',ds_store'];

I committed a comment to show that.

**Comment by Josema1982** [comment]
I'll try it, thanks for such a quick answer!

**Comment by jcampbell1** [comment]
No problem, you got lucky in caught me at the right time.
