### ISSUE TITLE
allow_create_folder = false|yes .   NO WORKING

### ISSUE THREAD

**Issue by paulgagu** [jcampbell1/simple-file-manager#57]
I checked and found a problem in line 434, should be $allow_create_folder instead $aloow_upload.

**Comment by markszabo** [comment]
Hey, I created a PR for this issue (#63), and it was implemented in 6403c5a, now being in master. I'd suggest to close this issue

**Comment by jcampbell1** [comment]
This should already be fixed.

**Comment by ikalkov** [comment]
@paulgagu, this can be closed.
