### ISSUE TITLE
Rename + Search !!!

### ISSUE THREAD

**Issue by ttcg52** [jcampbell1/simple-file-manager#6]
a Rename feature is really necessary... and a Search feature would be nice too... not to mention, a Drag and Move feature would pretty much complete this simple file manager !!

also, thanks for this script, simple and awesome at the same time !!!

**Comment by AngeIII** [comment]
I my fork rename feature available

**Comment by PhilJ88** [comment]
Nice one Angell, I'll check it out !

Another good little feature would be to have a yes/no alert box confirmation on pressing file delete buttons.

**Comment by AngeIII** [comment]
already have one:
```
var alert = confirm('are you sure want to delete?');
		if (!alert) { return false; }
```

**Comment by fgrimmer** [comment]
Any news about search feature?
Best regards,
Fernando Grimmer
