### ISSUE TITLE
Cannot list directories that contain plus (+) character

### ISSUE THREAD

**Issue by kdubowik** [jcampbell1/simple-file-manager#65]
First of all - great tool, thanks for creating it.
The problem I have is that directories whose name contain a plus character cannot be listed. This is the error response:

{"error":{"code":412,"msg":"Not a Directory"}}

However files whose filename contain a + can be downloaded without any problem.

**Comment by diego95root** [comment]
I just submitted a pull request with the modified script, just needed to encode some paths. I've got the file in my repo, in case you want to try it

**Comment by jcampbell1** [comment]
Thanks for the pull request.  Merged.

**Comment by diego95root** [comment]
You are welcome!
