### ISSUE TITLE
Bootstrap Fork

### ISSUE THREAD

**Issue by xcartmods** [jcampbell1/simple-file-manager#70]
Forked here - https://github.com/xcartmods/simple-file-manager

---

## Screenshot

![Screenshot](https://raw.github.com/xcartmods/simple-file-manager/master/screenshot.jpg "Screenshot")

![Screenshot](https://raw.github.com/xcartmods/simple-file-manager/master/screenshot2.jpg "Screenshot")

![Screenshot](https://raw.github.com/xcartmods/simple-file-manager/master/screenshot_3.jpg "Screenshot")

![Screenshot](https://raw.github.com/xcartmods/simple-file-manager/master/screenshot_4.jpg "Screenshot")

![Screenshot](https://raw.github.com/xcartmods/simple-file-manager/master/screenshot_5.jpg "Screenshot")

# ADDITIONS...

- New security setting - $THIS_FILENAME
- New security setting - $PASSWORD_STRONG
- Bootstrap v4, Bootswatch themes ($bootswatch_theme), responsive
- New login form, default password = ch@ng3me123$
- Images replaced with FontAwesome icons
- Icons for specific file types
- Modals for image, video and audio file types, all other files types load in new tab
- Optional advanced lightbox for image files ($lightgallery)
- Delete file confirm dialog setting ($delete_confirm)
- Full width layout setting ($full_width)
- Home, refresh and logout buttons
- Tested with PHP v7.2

**Comment by TuKo1982** [comment]
That fork was super, why has it been taken down ?

**Comment by Luca-Castelnuovo** [comment]
> That fork was super, why has it been taken down ?

Yes indeed.

**Comment by xcartmods** [comment]
I'll put it back up shortly, after I've applied some of the latest fixes... :)

**Comment by xcartmods** [comment]
Done
https://github.com/xcartmods/simple-file-manager
