### ISSUE TITLE
Hide directories

### ISSUE THREAD

**Issue by ikalkov** [jcampbell1/simple-file-manager#71]
Hi, is there a simple way to hide subdirectories from listing?

**Comment by jcampbell1** [comment]
No.

You could add
tr.is_dir { display: none }

to the CSS.

This is insecure, as it would be simple to reveal the rows from a browser
console.  Only use this hack if you are hiding the subfolders for aesthetic
reasons.

**Comment by ikalkov** [comment]
Oh, wow. Thanks for the fast response.
I'll use it for now, but I'm also OK with providing a proper solution (similar to hidden extensions). What is the state of this project? Are you accepting PRs?

**Comment by jcampbell1** [comment]
Yes, if it is a simple extension and doesn't change the goals of the
project.  Many people make major modifications, and I tell them to link to
the fork in the README.
