### ISSUE TITLE
Directory Traversal Bug

### ISSUE THREAD

**Issue by mirko911** [jcampbell1/simple-file-manager#73]
### Description
I found this bug in a fork of this software. It allows every registed user to download any file at the webserver root. 

### How to reproduce
- Open `<YOURPAGE>/index.php?do=download&file=index.php`

### Possible Solution

I think you should add a check if the filetype is allowed. Otherwise it's possible to download the index.php file and follow each include until you reach something interesting

https://github.com/jcampbell1/simple-file-manager/blob/master/index.php#L113

**Comment by jcampbell1** [comment]
fixed: cebe7f5
