### ISSUE TITLE
PHP Fatal error:  Call to undefined function mime_content_type() in... 

### ISSUE THREAD

**Issue by chillaz** [jcampbell1/simple-file-manager#79]
Hello,

Can someone please help me solve this server error. The error happens when I try to download any file from the server to the desktop when using the Chrome browser. The line where the error is happening is 116. I guess I am missing something here, but I don't know what it is.

116: `header('Content-Type: ' . mime_content_type($file));`

When I use the Firefox browser, I just get a blank page with nothing in it.

**Comment by jcampbell1** [comment]
I just changed it to something that should be more compatible.  It now uses
`finfo` rather than `mime_content_type()`

Try downloading the latest update.

**Comment by chillaz** [comment]
Hi jcampbell1

Finally got the hoster people to activate the finfo and I got the following error:

`PHP Fatal error:  Call to undefined function finfo_open() in filepath... on line 111, referer: filepath...`

Line 111 - `$finfo = finfo_open(FILEINFO_MIME_TYPE);`

**Comment by jcampbell1** [comment]
This is probably a PHP configuration that I am unable to support.
