### ISSUE TITLE
link whith %2F on link

### ISSUE THREAD

**Issue by gmoulard** [jcampbell1/simple-file-manager#80]
Hi 

On my file link, a dont have a right URL !!
I have : http://myServ/DD/timelaps%2FGMTimelaps%2Fcloud.pi0.253.vendredi.speed.mp4

But I need  http://myServ/DD/timelaps/GMTimelaps/cloud.pi0.253.vendredi.speed.mp4

My root directory is DD/timelaps.

Do you have some idéea ? 

G.

**Comment by czmole** [comment]
Hi, 

Which web server / version are you using?

Regarads,
Catalin

**Comment by Bryceed** [comment]
You can fix this bug changing this line
> .attr('href' data.is_dir ? '#' + encodeURIComponent(data.path) : './'+ encodeURIComponent(data.path))
> .attr('href', data.is_dir ? '#' + encodeURIComponent(data.path) : './'+ data.path)

...to remove the last URI encode.

Now is working fine here, on 7.2 👍

**Comment by webernetz** [comment]
Thx. Worked for me as well.

Can't someone change this in the original code as well?

**Comment by jcampbell1** [comment]
Thiis fixed in 222ab41
