### ISSUE TITLE
Feature Request: Option to List Folders First Before Files

### ISSUE THREAD

**Issue by ikwyl6** [jcampbell1/simple-file-manager#88]
As title suggests...

**Comment by ikwyl6** [comment]
I've created a diff file for this change. It also adds case insensitive to the file and directory listing. Could you please review and let me know if you have any comments,

[index.folder-first.diff.txt](https://github.com/jcampbell1/simple-file-manager/files/3006334/index.folder-first.diff.txt)

**Comment by jcampbell1** [comment]
I made directories on top the default.
