### ISSUE TITLE
Feature: Ability to go Up a Level Using Link

### ISSUE THREAD

**Issue by ikwyl6** [jcampbell1/simple-file-manager#89]
The area that shows "Home" > directory/directory1/directory2/directory3 should be separated links so you can click back into directory1 instead of clicking back button back->back to get to this directory.

**Comment by drumscream** [comment]
Hi! I just created pull request #93 to solve this problem.

**Comment by ikwyl6** [comment]
Tested pull request and works properly! thank you.
