### ISSUE TITLE
Hidden files

### ISSUE THREAD

**Issue by JonnyTech** [jcampbell1/simple-file-manager#90]
What is the correct way to hide "hidden files", ie files beginning with a dot such as `.htaccess` and `.ftpquota`?

This works for the above examples: `$hidden_extensions = ['php','htaccess','ftpquota'];` but it will not for others, is there a generic solution?

**Comment by jcampbell1** [comment]
This is fixed in 49790c0

Fixed by using glob style matching rather than extension based: 
`$hidden_patterns = ['*.php','.*'];`
