### ISSUE TITLE
Negative filesize on ARMv7 for files over 2GB

### ISSUE THREAD

**Issue by dausruddin** [jcampbell1/simple-file-manager#99]
Hi. I got an issue on my ARMv7 where files above 2GB will display negative size and needs a workaround in the code. I had this issue in https://github.com/prasathmani/tinyfilemanager/issues/127, so this might be good thread to refer regarding this issue.

Thanks

**Comment by jcampbell1** [comment]
This is a broader issue with PHP, and namely the call to `stat()`

**Comment by dausruddin** [comment]
Yes, which I was hoping you to implement the workaround. Anyway, thanks.
